server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: fly
          uri: lb://fly
          predicates:
            - Path=/api/*/fly/**
          filters:
            - AuthFilter
        - id: search
          uri: lb://search
          predicates:
            - Path=/api/*/search/**
        - id: security
          uri: lb://security
          predicates:
            - Path=/api/*/security/**, /api/*/user/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
  instance:
    hostname: localhost
